# Poster

We need to submit a two-page summary and any accompanying materials that help explain our work and that are indicative of what you will show at the poster session.

The summary should include
- concise description of the idea
- results of findings
- supporting figures
- discussion of the implications of the work to the selected domain
- relevant citations should be included

The submission **will be asked to refine** if it is accepted, based upon feedback from reviewers. Then, we need to prepare a poster.

Poster format: A0 size, portrait

Poster preview image: 1920 * 1080 (1080p)

*A video preview (25 seconds) cloud also be submitted (Sept 8).*

You need to submit the two-page summary and any accompanying materials that help explain your work and that are indicative of what you will show at the poster session. The electronic poster itself only needs to be prepared for accepted submissions. Detailed description regarding submission of final content will be provided after acceptance to the conference.
